### ISSUE TITLE
 the "submit" button of a form is an <input> element with a type of "submit", not a <button> element.

### ISSUE THREAD

**Issue by ff18qd** [learn-co-curriculum/sinatra-basic-forms-lab#16]
In the course it requires an <input> element with a type of "submit", not a <button> element. However, spec is still looking for a button not an input with type submit. 
App POST / displays the puppy
     Failure/Error: click_button "submit"
     Capybara::ElementNotFound:
       Unable to find button "submit"

**Comment by maxwellbenton** [comment]
Hello there,

Although the testing environment we are using, Capybara, uses the term 'click_button', the current tests will pass whether you use an <input /> or <button /> element.  The key is that Capybara is looking for specific attributes, 'id', 'value', or 'title' when running the test, so one of these is required in the element.
