### ISSUE TITLE
uninitialized constant error won't allow for proper test running

### ISSUE THREAD

**Issue by independnt** [learn-co-curriculum/sinatra-basic-forms-lab#18]
missing require 'capybara/dsl' under spec_helper.rb for proper functioning

**Comment by ThePeej** [comment]
thanks for this. c in require capybara (above) should be lower case

**Comment by independnt** [comment]
thanks! updated.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated spec_helper.rb.

As always thank you for contributing.
