### ISSUE TITLE
Would be helpful if there were clear instructions on what the website should do...

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/sinatra-basic-forms-lab#20]
Like, what is the overall point of this lab? What is the gist of it? What is it supposed to do? It's not helpful just knowing that there needs to be an attr_accessor... we need the overall point of the program first. Half of these labs are the same - the instructions are basically missing. 

For example, if i'm describing what a car is, I don't start with: the car should have windows that roll down, the floor mats will gather water and particles, speakers will play music, etc. 

You start with: a car is a vehicle meant to transport passengers. It is driven by one person in the vehicle using a steering wheel. It has four wheels that hold it's weight. 

That is how you write instructions.

**Comment by sgharms** [comment]
Thank you for this general feedback. While I don't see that we're discussing attr_accessor specifically in this lab, your suggestion to ensure that learning objectives come before requirements and implementation is valid. We will look to schedule a harmonizing series of works in the upcoming quarters.

We will be closing this issue on this repo (as your observation applies to multiple repos). If you have specific feedback about this repository, please re-open and specify.

Thank you, 💙
