### ISSUE TITLE
Difference Between Route Described In Spec And Route EXPECTED In Spec

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/sinatra-basic-forms-lab#21]
In the `sinatra_basic_forms_lab_spec`, the description has the route listed as 'GET /NEW', but the test itself is expecting to find a route in lowercase '/new'. Seeing as how the description is what gets listed during the spec output of learn, this led me to some confusion until I realized the difference in case mattered.

The description should be updated to match the lowercase expectations of the spec.

**Comment by cjbrock** [comment]
Thanks for your feedback!

// Corinna
