### ISSUE TITLE
variable name inconsistent

### ISSUE THREAD

**Issue by peidansauyukjuk** [learn-co-curriculum/sinatra-basic-forms-lab#30]
Rspec tests want us to use pupper.months_old when passing in a hash but the tests want pupper.age.

**Comment by maxwellbenton** [comment]
Hi @peidansauyukjuk,

Thank you for spotting this and providing feedback. We've fixed the inconsistent variables, updated the tests, readme and solution, and believe this issue has been resolved. Thank you for helping to make this lesson better for future students!

**Comment by dwyn** [comment]
+1
