### ISSUE TITLE
Make the link text consistent across starter code, test, and solution.

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/sinatra-basic-forms-lab#31]
**Premise**

The purpose of this lab, as stated in the `README`, is to build understanding of how user actions (initiating a request) connect to the controller, model, and ultimately the response they receive.

**Problem Statement / Analysis**

With the following git commits over the history of this lab, there have been updates to the lab starter code, tests, and solution branches that have caused the `<a>` link tag's text to become out of sync. _**It confuses the students as it becomes a debugging exercise on how Capybara works and detracts from the actual purpose of the lab.**_

These are the commits that change the expected text to be _Link a/A Puppy_ instead of the original (and still present) _Click Here To List A Puppy_:

* [4060fd23e258ba1381f80aebd5a37fe47120f782](https://github.com/learn-co-curriculum/sinatra-basic-forms-lab/commit/4060fd23e258ba1381f80aebd5a37fe47120f782) - This is the commit that updated the rspec test to be better. However, it didn't update the starter code to match.
* [c01b958aa58e988efa8719b12e050ed0beb0a67d](https://github.com/learn-co-curriculum/sinatra-basic-forms-lab/commit/c01b958aa58e988efa8719b12e050ed0beb0a67d) - Corresponding solution branch fix that updates the view with the new test expectation.

These are the string of commits that later try to fix the `a` vs `A` capitalization inconsistency between the test and the solution branch:

* [3467f6a74ab174634e27b200f7d2cc7444fae8d3](https://github.com/learn-co-curriculum/sinatra-basic-forms-lab/commit/4060fd23e258ba1381f80aebd5a37fe47120f782)
* [78b5aa2a78f56015689c903d14c513962f61635a](https://github.com/learn-co-curriculum/sinatra-basic-forms-lab/commit/4060fd23e258ba1381f80aebd5a37fe47120f782)
* [f5eae1fddd7db24b64b0ce8f03f6b0f696b5ab97](https://github.com/learn-co-curriculum/sinatra-basic-forms-lab/commit/f5eae1fddd7db24b64b0ce8f03f6b0f696b5ab97)
* etc. as there are more

None of these catch the issue of the starter code for `sinatra-basic-forms-lab/views/index.erb` never being updated to have default link text matching what is in the rspec test.

**Proposed Solution**

Please correct the starter code's link text in `sinatra-basic-forms-lab/views/index.erb` to be consistent with what is expected by the rspec test and to be consistent with the solution branch's `index.erb` code and rspec test. If the student wires up their controller correctly, that link test should automatically pass without having to touch `index.erb`.

**Comment by gzavaglia** [comment]
I was going to say the same thing. It drove me crazy thinking my code was wrong.

**Comment by AudTheCodeWitch** [comment]
Thanks for this! I was going crazy trying to figure out why the tests weren't passing.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
