### ISSUE TITLE
Tests need revision

### ISSUE THREAD

**Issue by Dwake5** [learn-co-curriculum/sinatra-basic-forms-lab#32]
Confusing spec - puppy initialize declares `months_old` but most tests are looking for `age`

Please revise to use one or the other throughout - we had to change the test file and replace all instances of `months_old` with `age` to get functionality in browser and tests to pass

**Comment by Sdcrouse** [comment]
It looks like there's a pull request for that; it just hasn't been implemented yet.

That said, I found another solution that students can use in the meantime, without having to alter the tests themselves. In the Puppy class, you can add this code below the attr_accessor:

```
alias_method :age, :months_old
alias_method :age=, :months_old=
```
That allows any class to use the Puppy class's #months_old reader and writer methods under the #age and #age= aliases. For example, `new_puppy.months_old = 5` and `new_puppy.age = 5` can now do the same thing!

You could also do something in the controller like this:
```
new_puppy = Puppy.new(params[:name], params[:breed], params[:age]) 
# or use "months_old: params[:age]", if the puppy is initialized with a hash

@age = new_puppy.months_old
```
...But I think #alias_method is easier to understand, and less prone to bugs.

This obviously makes the lab more complicated than it needs to be, but it's nice to know what else Ruby can do!

---Sdcrouse

**Comment by regilfillan** [comment]
params still has :age, not :months_old, so in POST is the only place I had to type :age, everywhere else said :months_old.  my code was not very pretty in order to pass...

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
