### ISSUE TITLE
Rspec Tests looking for capital A

### ISSUE THREAD

**Issue by aparkening** [learn-co-curriculum/sinatra-basic-forms-lab#33]
Not sure if this is a feature or a bug! The tests for "Get /" fail because sinatra_basic_forms_lab_spec.rb is looking for "List a Puppy", and your default index.erb has "List A Puppy". I needed to change the "A" to lowercase to get the tests to pass.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
