### ISSUE TITLE
404 Fork this lab route

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/sinatra-basic-forms-lab#8]
Fork this lab points to a 404 page.

Link to lab on learn curriculum page https://github.com/learn-co-curriculum/sinatra-basic-forms-lab

**Comment by AnnJohn** [comment]
thanks @jakebrady5 we're looking into it and should have it fixed soon.

**Comment by AnnJohn** [comment]
hi @jakebrady5 this should be fixed now. Thanks!
